In [1]:
import pandas as pd
import numpy as np

from src.cleaning import (
    fill_missing_median,
    drop_missing,
    normalize_data
)

In [2]:
df = pd.read_csv(
    "data/raw/starter_data.csv"
)

df.head

<bound method NDFrame.head of   category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05
5        C     30  2025-08-06
6        A     11  2025-08-07
7        B     14  2025-08-08
8        C     28  2025-08-09
9        A     13  2025-08-10>

In [3]:
df.info()

print("\nMissing values:")
print(df.isna().sum())

print("\nShape:", df.shape)

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  10 non-null     str
 1   value     10 non-null     int64
 2   date      10 non-null     str
dtypes: int64(1), str(2)
memory usage: 482.0 bytes

Missing values:
category    0
value       0
date        0
dtype: int64

Shape: (10, 3)

In [4]:
df_original = df.copy()
df_cleaned = df.copy()

df_cleaned = fill_missing_median(
    df_cleaned,
    columns=["value"]
)

print(df_cleaned.isna().sum())

category    0
value       0
date        0
dtype: int64

In [5]:
print("Rows before:", len(df_original))
print(
    "Rows after missing-value handling:",
    len(df_cleaned)
)

Rows before: 10
Rows after missing-value handling: 10

In [6]:
df_cleaned["date"] = pd.to_datetime(
    df_cleaned["date"]
)

print(
    "Original date dtype:",
    df_original["date"].dtype
)

print(
    "Cleaned date dtype:",
    df_cleaned["date"].dtype
)

Original date dtype: str
Cleaned date dtype: datetime64[us]

In [7]:
df_cleaned = normalize_data(
    df_cleaned,
    columns=["value"],
    method="minmax"
)

In [8]:
df_cleaned

  category  value       date
0        A   0.00 2025-08-01
1        B   0.25 2025-08-02
2        A   0.10 2025-08-03
3        B   0.40 2025-08-04
4        C   0.75 2025-08-05
5        C   1.00 2025-08-06
6        A   0.05 2025-08-07
7        B   0.20 2025-08-08
8        C   0.90 2025-08-09
9        A   0.15 2025-08-10

In [9]:
print("Original shape:", df_original.shape)
print("Cleaned shape:", df_cleaned.shape)

print("\nOriginal missing values:")
print(df_original.isna().sum())

print("\nCleaned missing values:")
print(df_cleaned.isna().sum())

print("\nOriginal dtypes:")
print(df_original.dtypes)

print("\nCleaned dtypes:")
print(df_cleaned.dtypes)

print("Original numeric summary:")
display(df_original.describe())

print("Cleaned numeric summary:")
display(df_cleaned.describe())

display(df_original)
display(df_cleaned)

Original shape: (10, 3)
Cleaned shape: (10, 3)

Original missing values:
category    0
value       0
date        0
dtype: int64

Cleaned missing values:
category    0
value       0
date        0
dtype: int64

Original dtypes:
category      str
value       int64
date          str
dtype: object

Cleaned dtypes:
category               str
value              float64
date        datetime64[us]
dtype: object
Original numeric summary:

           value
count  10.000000
mean   17.600000
std     7.381659
min    10.000000
25%    12.250000
50%    14.500000
75%    23.250000
max    30.000000

Cleaned numeric summary:

           value                 date
count  10.000000                   10
mean    0.380000  2025-08-05 12:00:00
min     0.000000  2025-08-01 00:00:00
25%     0.112500  2025-08-03 06:00:00
50%     0.225000  2025-08-05 12:00:00
75%     0.662500  2025-08-07 18:00:00
max     1.000000  2025-08-10 00:00:00
std     0.369083                  NaN

  category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05
5        C     30  2025-08-06
6        A     11  2025-08-07
7        B     14  2025-08-08
8        C     28  2025-08-09
9        A     13  2025-08-10

  category  value       date
0        A   0.00 2025-08-01
1        B   0.25 2025-08-02
2        A   0.10 2025-08-03
3        B   0.40 2025-08-04
4        C   0.75 2025-08-05
5        C   1.00 2025-08-06
6        A   0.05 2025-08-07
7        B   0.20 2025-08-08
8        C   0.90 2025-08-09
9        A   0.15 2025-08-10

In [10]:
output_path = (
    "data/processed/starter_data_cleaned.csv"
)

df_cleaned.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)

Saved: data/processed/starter_data_cleaned.csv

## Preprocessing Assumptions and Reflection

`fill_missing_median()` and `drop_missing()` were applied as part of
the preprocessing workflow but did not alter the dataset, because the raw dataset contained no missing values. No values needed to be imputed and no observations were removed.

The `date` column was converted from text to a datetime data type.

The `value` column was normalized using MinMaxScaler, placing the
observations on a common scale from 0 to 1 while preserving their
ordering and proportional distances.  This was appropriate considering
that the dataset contained no extreme outliers.

The cleaned dataset retains all 10 original observations. The primary
changes are the corrected date type and normalization of the numeric
`value` feature.

Median imputation would preserve observations if numeric values were
missing, but it could reduce natural variation in the data. Dropping
missing observations avoids creating artificial values but can reduce
sample size or introduce bias if the missingness is systematic.
Neither tradeoff affected this dataset because no values were missing.